
package br.com.projecti.cip.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControleGarantia", targetNamespace = "http://webservice.scg.cipbancos.org.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControleGarantia {


    /**
     * 
     * @param scgRequest
     * @return
     *     returns br.com.projecti.cip.cliente.SCGResponse
     */
    @WebMethod
    @WebResult(name = "scgResponse", targetNamespace = "http://webservice.scg.cipbancos.org.br", partName = "scgResponse")
    public SCGResponse executeOperation(
        @WebParam(name = "scgRequest", targetNamespace = "http://webservice.scg.cipbancos.org.br", partName = "scgRequest")
        SCGRequest scgRequest);

    /**
     * 
     * @param confirmation
     * @return
     *     returns br.com.projecti.cip.cliente.SCGResponse
     */
    @WebMethod
    @WebResult(name = "scgResponse", targetNamespace = "http://webservice.scg.cipbancos.org.br", partName = "scgResponse")
    public SCGResponse retryByConfirmationOperation(
        @WebParam(name = "confirmation", targetNamespace = "http://webservice.scg.cipbancos.org.br", partName = "confirmation")
        String confirmation);

    /**
     * 
     * @param id
     * @return
     *     returns br.com.projecti.cip.cliente.SCGResponse
     */
    @WebMethod
    @WebResult(name = "scgResponse", targetNamespace = "http://webservice.scg.cipbancos.org.br", partName = "scgResponse")
    public SCGResponse retryByIdOperation(
        @WebParam(name = "id", targetNamespace = "http://webservice.scg.cipbancos.org.br", partName = "id")
        String id);

}
